name: Build Telegram Desktop

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install CMake, Git, and VSWhere
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
          choco install git -y
          choco install vswhere -y

      - name: Set up MSVC environment
        shell: cmd
        run: |
          for /f "delims=" %%i in ('vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath') do set VSINSTALLDIR=%%i
          call "%VSINSTALLDIR%\VC\Auxiliary\Build\vcvars64.bat"
          set

      - name: Download Qt Online Installer
        run: |
          Invoke-WebRequest -Uri "https://download.qt.io/official_releases/online_installers/qt-unified-windows-x64-online.exe" -OutFile qt-installer.exe

      - name: Create Qt install script
        run: |
          Set-Content -Path qt-install-script.qs -Value 'var installer = new QInstaller();'
          Add-Content -Path qt-install-script.qs -Value 'var components = ["qt.qt5.5152.win64_msvc2019"];'
          Add-Content -Path qt-install-script.qs -Value 'installer.setValue("components", components);'
          Add-Content -Path qt-install-script.qs -Value 'installer.setValue("installationPath", "C:/Qt/Qt5.15.2");'
          Add-Content -Path qt-install-script.qs -Value 'installer.setValue("autoAccept", true);'
          Add-Content -Path qt-install-script.qs -Value 'installer.setValue("acceptLicense", true);'
          Add-Content -Path qt-install-script.qs -Value 'installer.setValue("skipUpdate", true);'
          Add-Content -Path qt-install-script.qs -Value 'installer.install();'

      - name: Install Qt
        run: |
          Start-Process -FilePath qt-installer.exe -ArgumentList '--script qt-install-script.qs' -Wait
        shell: pwsh

      - name: Clone and prepare source
        run: |
          git clone --recursive https://github.com/TDesktop-x64/tdesktop.git
          cd tdesktop\Telegram\build
          .\prepare\win.bat

      - name: Configure
        run: |
          cd tdesktop\Telegram
          .\configure.bat x64 -D TDESKTOP_API_ID=${{ secrets.TDESKTOP_API_ID }} -D TDESKTOP_API_HASH=${{ secrets.TDESKTOP_API_HASH }}

      - name: Build
        run: msbuild tdesktop\out\Telegram.sln /p:Configuration=Release
