name: Build Telegram Desktop

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install CMake
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y

      - name: Install Git
        run: choco install git -y

      - name: Download Qt Online Installer
        run: |
          Invoke-WebRequest -Uri "https://download.qt.io/official_releases/online_installers/qt-unified-windows-x64-online.exe" -OutFile qt-installer.exe

      - name: Install Qt
        run: |
          Start-Process -FilePath qt-installer.exe -ArgumentList '--silent --accept-messages --no-replace --no-updates --default-setup --modules qt.qt5.5152.win32_msvc2019' -Wait
        shell: pwsh

      - name: Clone and prepare source
        run: |
          git clone --recursive https://github.com/TDesktop-x64/tdesktop.git
          cd tdesktop\Telegram\build
          .\prepare\win.bat

      - name: Configure
        run: |
          cd tdesktop\Telegram
          .\configure.bat x64 -D TDESKTOP_API_ID=${{ secrets.TDESKTOP_API_ID }} -D TDESKTOP_API_HASH=${{ secrets.TDESKTOP_API_HASH }}

      - name: Build
        run: msbuild tdesktop\out\Telegram.sln /p:Configuration=Release
